name: 'Validate'
on:
  - pull_request
jobs:
  terraform:
    strategy:
      fail-fast: false
      matrix:
        stack:
          - .
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: 'eu-central-1'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@v0.8.0
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ matrix.stack }}
          tf_actions_comment: false
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@v0.8.0
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ matrix.stack }}
          tf_actions_comment: false
          args: '-backend=false'
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@v0.8.0
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ matrix.stack }}
          tf_actions_comment: false
